
spring:
  application:
    name: admin #在Eureka Server注册的服务名
  boot:
    admin:
      client:
        url: http://localhost:8080

eureka:
  instance:
    non-secure-port: ${server.port:8888} #非SSL端口，若环境变量中server.port有值，则使用环境变量的值，没有则使用8080
    metadata-map:
      instanceId: ${spring.application.name}:${random.value} #配置在Eureka Server的实例ID
  client:
    service-url:
      defaultZone: http://${eureka.host:localhost}:${eureka.port:8761}/eureka/ #Eureka 客户端设置Eureka Server的地址
